import { useState } from "react";
import "@/scss/global.scss";
import { Inter } from "next/font/google";
import { ContextProvider } from "@/app/context/GlobalContext";

export const metadata = {
  title: "Cryptospace Card",
  description: "Generated by Next.js",
};

const inter = Inter({
  weight: ["300", "400", "500", "700", "800"],
  style: ["normal"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    
      <html lang="en">
        
        <body className={inter.className}>
          <ContextProvider>
          {children}
          </ContextProvider>
          </body>
      </html>
  );
}
