export type CardProfileType = {
  countryOrigin: string,
  countryResidency: string,
  userData: any,
  documentImage: string,
  cardType: string,
  deliveryType: string,
  plan: string,
  seller: string,
  totalPrice: number,
  screen: string,
  page: number,
  setCountryOrigin: (value: string) => void,
  setCountryResidency: (value: string) => void,
  setScreen: (value: any) => void,
  setPage: (value: number) => void,
  setUserData: (value: any) => void,
  setDocumentImage: (value: string) => void,
  setCardType: (value: string) => void,
  setDeliveryType: (value: string) => void,
  setPlan: (value: string) => void,
  setSeller: (value: string) => void,
  setTotalPrice: (value: number) => void,
}